# Generated by Django 5.0.6 on 2024-07-17 17:59

import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTenure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.ImageField(default='img.png', upload_to='agentimages')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.location')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_description', models.CharField(max_length=1000)),
                ('property_address', models.CharField(max_length=100)),
                ('property_price', models.FloatField()),
                ('property_bedrooms', models.IntegerField()),
                ('agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='properties.agents')),
                ('property_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.location')),
                ('property_tenure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.propertytenure')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.image_file_path)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.properties')),
            ],
        ),
    ]
