# Generated by Django 5.0.6 on 2024-07-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
    ]
