# Generated by Django 5.1 on 2024-08-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertytenure_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_description',
            field=models.CharField(max_length=10000),
        ),
    ]
