# Generated by Django 5.0.6 on 2024-07-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_properties_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
