# Generated by Django 5.1 on 2024-08-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_userresponse_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField(max_length=50000)),
            ],
        ),
    ]
