# Generated by Django 5.1 on 2024-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='Not set', upload_to='blogs'),
        ),
    ]
